name: Build sphinx documentation

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install ghp-import
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build HTML
        run: | 
          cd docs/
          make html
      - name: Run ghp-import
        run: | 
          ghp-import -n -p -f -o docs/build/html
          